services:
    php:
        container_name: php-fpm
        build:
            context: ./
            dockerfile: "./docker/php/Dockerfile"
            args:
                user: sammy
                uid: 1000
        environment:
            XDEBUG_CONFIG: "remote_host={{127.0.0.1}}"
            PHP_IDE_CONFIG: "serverName=host.docker.internal"
        working_dir: /var/www/html
        ports:
            - "5173:5173"
        networks:
            - caddy_network
        volumes:
            - ./:/var/www/html:cached
            - ../portainer/caddy_data/caddy/certificates/local/movies.localhost:/var/www/html/docker/cert
            - ./node_modules:/var/www/html/node_modules:delegated
            - ./public:/var/www/html/public:delegated

#    nginx:
#        container_name: movie-nginx
#        image: nginx
#        environment:
#            NGINX_STATIC_OPEN_FILE_CACHE: "off"
#            NGINX_ERROR_LOG_LEVEL: debug
#            NGINX_BACKEND_HOST: php
#            NGINX_VHOST_PRESET: php
#            NGINX_SERVER_ROOT: /var/www/html/public
#        volumes:
#            - ./docker/nginx:/etc/nginx/conf.d/
#            - ./public:/var/www/html/public:delegated
#            - ./storage/app/public:/var/www/html/storage/app/public:delegated
#        networks:
#            - traefik_network
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.movie-app.tls=false"
#            - "traefik.http.routers.movie-app.rule=Host(`movie-app.localhost`)"

#    mysql-movie:
#        image: mysql
#        volumes:
#            - ./docker/mysql:/var/lib/mysql:rw
#        environment:
#            MYSQL_DATABASE: db
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_USER: db
#            MYSQL_PASSWORD: db
#        ports:
#            -   '34000:3306'
#        networks:
#            - caddy_network

#  mailhog:
#    image: mailhog/mailhog
#    container_name: movie-mailhog
#    networks:
#      - default
#      - traefik-gateway
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=traefik-gateway"
#      - "traefik.http.services.movie-mailhog.loadbalancer.server.port=8025"
#      - "traefik.http.routers.movie-mailhog.rule=Host(`mailhog.movie-filemaker-jamf-integration.localhost`)"
#      - "traefik.http.routers.movie-mailhog.entrypoints=https"
#      - "traefik.http.routers.movie-mailhog.tls=true"

#volumes:
#    redis:
#        driver: local

networks:
    caddy_network:
        external: true
